### ISSUE TITLE
Conflict with Quicksand/Portfolio

### ISSUE THREAD

**Issue by dlzi** [arnaudleray/pocketgrid#2]
Hi there,

I don't know where is the problem, but when I use pocketgrid with my portfolio, Quicksand gets weird. I used the follow tuts http://wp.tutsplus.com/tutorials/theme-development/create-a-quicksand-portfolio-with-wordpress/ as the base for my portfolio. If I decide to use pocketgrid, the quicksand transitions (effects) stop working.

Any idea?

**Comment by arnaudleray** [comment]
Hi,

I'm quite busy for the moment (I'm preparing a new official site for PocketGrid) so I cannot test the tutorial you followed.

Maybe your problem is due to the QuickSand transitions which may not be compatible with CSS floats?

Can you put your portfolio online so that I can test it to see what's wrong?
Or could you make your source code available? (on Github or with a zip file I could download?)

**Comment by dlzi** [comment]
Hi,

Sorry, I'm working locally. Once I've done I can send you the link. However, I think you nailed. The transitions issue is due the CSS floats. Once I comment for example the <b>.block</b> , things start working again.

So, I think I'll have to leave the grid out of my portfolio page.

**Comment by arnaudleray** [comment]
Most (if not all) grid systems use floats, so I think your problem is not really a PocketGrid bug.

Let me know when you can put your portfolio online.

Thanks.

**Comment by dlzi** [comment]
You are right. It's not a PocketGrid bug.

I'll close this issue since it wasn't related to PocketGrid.
Sorry about that.

Thanks.
